### ISSUE TITLE
Проблемы с загрузкой класса io.netty.bootstrap.Bootstrap 

### ISSUE THREAD

**Issue by bostandyksoft** [sbtqa/page-factory-2-example#16]
Проект содержит транзитивные зависимости и с пакетами
io.netty:netty-all:4.0.51.Final и io.netty:netty-transport:4.1.87.Final

![image](https://github.com/sbtqa/page-factory-2-example/assets/4920442/3900505b-58bd-4f79-a00b-6bad6dfbfe25)

И в том, и в другом есть класс io.netty.bootstrap.Bootstrap разных версий, поэтому "успешность" запуска зависит от того, какой класс будет загружен Classloader.

При попытке выровнить версию io.netty:netty-all до 4.1.87 средствами Gradle ошибки создания Bootstrap не появляется, но websocket не может получить соединение к браузеру.

Есть идеи как это фиксить?

PS Посмотрел - в предыдущей версии транзитивные зависимости были только на netty-all, а не на кучу netty-  пакетов.

**Comment by kosteman** [comment]
закрыто как дубликат https://github.com/sbtqa/page-factory-2/issues/392
